### ISSUE TITLE
Lucee 5 and Ubuntu 16.04 LTS Support

### ISSUE THREAD

**Issue by pfreitag** [foundeo/ubuntu-nginx-lucee#11]
This script needs to be updated for both Lucee 5 and Ubuntu 16.04 LTS.

My thoughts are to take the current master branch and create a new branch called `lucee45-ubuntu14` and then update master to work with Lucee 5 and Ubuntu 16.04 - the main differences in 16.04 is that it includes Tomcat 8 instead of Tomcat 7.

Ideally the master (lucee 5) branch would still work with Ubuntu 14.04 as well.

Pull request #10 from @andyj adds Lucee 5 support but it uses the Viviotech installer which includes a bundled version of tomcat (so you have to patch tomcat manually).

**Comment by andyj** [comment]
That sounds great.

Tbh bin my pull request. It's not right.

**Comment by al3x-edge** [comment]
@pfreitag Can you create a new Lucee 5 / Ubuntu 16.04 branch to accept pull requests into?

**Comment by pfreitag** [comment]
@al3x-edge I have created a lucee5 branch.

**Comment by pfreitag** [comment]
@al3x-edge thanks for your PR to add Lucee 5 support. Ubuntu 16.04 supports either `tomcat7` or `tomcat8`, we should probably add a variable `TOMCAT_VERSION` and use that throughout the scripts to add tomcat8 support. The main bit of work there is to add `etc/tomcat8` with appropriate changes.

**Comment by al3x-edge** [comment]
@pfreitag Sounds like a great idea.  I'll add that in.

**Comment by joshuairl** [comment]
Did this ever go anywhere?

**Comment by pfreitag** [comment]
@joshuairl yes the master branch has been switched to lucee 5, I don't think we have added a `TOMCAT_VERSION` option yet however.

**Comment by pfreitag** [comment]
I haven't added the `TOMCAT_VERSION` variable but I have updated the scripts to use tomcat8, if you really want to use `tomcat7` you can edit the scripts I don't think there is much need to support tomcat7 at this point.
