### ISSUE TITLE
mod_cfml failing to download when running install.sh

### ISSUE THREAD

**Issue by JasPanesar** [foundeo/ubuntu-nginx-lucee#13]
Hi, this installer is providing the following error which appears to be preventing a working installation of lucee.  I am using restore points on a Digital Ocean VM to roll back installation attempts in the hopes of having the installer run successfully.

```
Installing mod_cfml Valve for Automatic Virtual Host Configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: /opt/lucee/current/mod_cfml-valve_v1.1.05.jar: No such file or
```

I believe it may be related to scripts/300-tomcat.sh approx line 32:

```
 29 echo "Installing mod_cfml Valve for Automatic Virtual Host Configuration"
 30 if [ -f lib/mod_cfml-valve_v1.1.05.jar ]; then
 31   cp lib/mod_cfml-valve_v1.1.05.jar /opt/lucee/current/
 32 else
 33   curl --location -o /opt/lucee/current/mod_cfml-valve_v1.1.05.jar https://raw.githubusercontent.com/utdream/mod_cfml/master/java/mod_cfml-valve_v1.1.05.jar
 34 fi
```

Investigating further..

**Comment by JasPanesar** [comment]
This modified command appears to download the mod_cfml.  Unsure if it's the best source to pull on from Github but seemed to work.

`curl --location -o mod_cfml-valve_v1.1.05.jar https://github.com/utdream/mod_cfml/blob/master/java/mod_cfml-valve_v1.1.05.jar?raw=true`

**Comment by pfreitag** [comment]
I don't think it is the URL that is bad, I think the /opt/lucee/current directory does not exist because this line is not running:

`ln -s /opt/lucee/$jar_folder /opt/lucee/current`

I haven't figured out why it is not creating the link yet, but that seams to be an issue someone else had running it the other day.

**Comment by JasPanesar** [comment]
I didn't have a chance to update this, I noticed the link was not being created as well.  

When I moved that line into the main install.sh file between the commands of the 200-lucee.sh and 300-tomcat.sh it seemed to create the linked directory, but there were still some errors.  I will circle back and confirm the above is no longer an issue.  Thanks for the quick reply! Great project.

**Comment by pfreitag** [comment]
Thanks, let me know what you find, I can't see any reason why the link isn't getting created where it currently is located in the 200-lucee.sh file, but I haven't had a chance to test it out yet.
