### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by malpaso** [foundeo/ubuntu-nginx-lucee#17]
I don't think the permissions in the install scripts are quite up to par. I had to add quite a few more to get 'www-data' to access a new site made under /web

Furthermore, running a CF file for the first time and this error is encountered:

javax.servlet.ServletException: can't create directory /web/mywebsite/wwwroot/WEB-INF/lucee

So it seems that Lucee/Tomcat isn't allowed to touch the new directory? How do I resolve this?

**Comment by malpaso** [comment]
Fixed this by doing the following:

mkdir /web/mywebsite/wwwroot/WEB-INF
sudo chown tomcat7:tomcat7 /web/mywebsite/wwwroot/WEB-INF

**Comment by pfreitag** [comment]
This is fixed in the script, so it doesn't put the `WEB-INF` in the webroot, it places it in under the `/opt/lucee/config/` folder.
