### ISSUE TITLE
Unabe to install Tomcat8 - error in script

### ISSUE THREAD

**Issue by wgregori** [foundeo/ubuntu-nginx-lucee#19]
Trying to install on Ubuntu 14.04 server - 

Installing Tomcat 8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tomcat8

**Comment by wgregori** [comment]
saw that it is only tested with 16.04... works there.  Thanks

**Comment by pfreitag** [comment]
Yes for 14.04 you have to use tomcat7, this branch installs Lucee 4.5 on Ubuntu 14.04 if interested: https://github.com/foundeo/ubuntu-nginx-lucee/tree/lucee45-ubuntu14
