### ISSUE TITLE
 login to /lucee/admin/server.cfm - does not work

### ISSUE THREAD

**Issue by wgregori** [foundeo/ubuntu-nginx-lucee#20]
I successfully executed the scripts to install Lucee... added my ip to lucee.conf but above path added to my ip address does not work (http://myipaddress/lucee/admin/server.cfm).  Additionally, http://myip:8888 will not work. But http://myipaddress:8080 show a successful Tomcat8 installation.  It looks like I have an "almost" successful installation.  How can I proceed?  thanks

**Comment by pfreitag** [comment]
@wgregori does your `/etc/tomcat8/web.xml` file look like this: https://github.com/foundeo/ubuntu-nginx-lucee/blob/master/etc/tomcat8/web.xml

**Comment by johnjarrard** [comment]
I am having this same issue.  I installed using your script, made it use the latest version of Lucee (5.1.3.18) and mae sure my tomcat8/web.xml script matches exactly what is above.  Nginx is running just fine.  Just can't get the /lucee/admin/server.cfm to work - it returns a 404.

**Comment by pfreitag** [comment]
@johnjarrard did you edit the `/etc/nginx/lucee.conf` file to allow your IP address? See https://github.com/foundeo/ubuntu-nginx-lucee/blob/master/etc/nginx/lucee.conf#L5

**Comment by johnjarrard** [comment]
Yes, I did.  I blew away the VM and tried again and it worked.

**Comment by pfreitag** [comment]
Ok thanks, closing this issue.
