### ISSUE TITLE
Lucee is running on port 8080

### ISSUE THREAD

**Issue by richardhughes260** [foundeo/ubuntu-nginx-lucee#24]
Thanks for this installation!!! :)

Lucee is running on Port 8080, you might want to add that to the instructions.

**Comment by iamenderst** [comment]
In /etc/nginx/sites-enabled/default.conf

add
include lucee.conf;

after
index index.html;

Then you can access /lucee/admin/server.cfm as in the instructions.

Now you can block 8080 from the outside world.

**Comment by dcabram** [comment]
I'm getting

502 Bad Gateway

when trying to access

http://{my_ip}/lucee/admin/server.cfm

any ideas ?

**Comment by pfreitag** [comment]
@dcabram usually that means that tomcat is not running - since that question is unrelated to this issue, please open a new issue if you are stilling having a problem.
