### ISSUE TITLE
Misspelling in instructions: "sites-avaliable" should be "sites-available"

### ISSUE THREAD

**Issue by jasonmcneill** [foundeo/ubuntu-nginx-lucee#26]
Minor correction:

In the instructions, under "[Setting up a virtual host](https://github.com/foundeo/ubuntu-nginx-lucee#setting-up-a-virtual-host)," you have the following misspelled nginx directory:
`/etc/nginx/sites-avaliable/`

It should be:
`/etc/nginx/sites-available/`

**Comment by pfreitag** [comment]
Thanks @jasonmcneill fixed!
