### ISSUE TITLE
How is OpenJDK used/setup?

### ISSUE THREAD

**Issue by malpaso** [foundeo/ubuntu-nginx-lucee#27]
I have run the scripts as suggested (commenting out the $JVM_FILE env variable) and everything seemingly installs however LUCEE will not run, the nginx web server is up and available. I have a feeling that there is no JVM available. Tomcat is saying it cannot start Lucee

What am I doing wrong here in regards to simply running these scripts?

This is on a fresh Ubuntu installation on Digital Ocean.

**Comment by pfreitag** [comment]
Can you post the snippets from the logs where Tomcat says it cannot start Lucee?

If tomcat is getting that far, then you do have java installed. OpenJDK is a dependency of tomcat, so it gets installed when you install tomcat if it was not there already. You can run `java -version` to double check.

**Comment by pfreitag** [comment]
@malpaso haven't heard back - do you have any further questions, if not I will close the issue?

**Comment by kwfricke** [comment]
I am at a loss. I have tried to get this to work and have not had success. I am running this on a new droplet with DO. I can't seem to get any of the admins to work. When I try to access the IP address with port 8080 my browser just spins. Is there a walk through of what to do once you are done with the install?

**Comment by pfreitag** [comment]
@kwfricke The Lucee Admin is blocked by default - you need to edit `/etc/nginx/lucee.conf` and add a line to allow your IP, take a look here:

https://github.com/foundeo/ubuntu-nginx-lucee/blob/master/etc/nginx/lucee.conf#L5
