### ISSUE TITLE
Write access?

### ISSUE THREAD

**Issue by iamenderst** [foundeo/ubuntu-nginx-lucee#29]
How do I give Lucee write access to the web root? Been messing with permissions etc... with no love.

**Comment by pfreitag** [comment]
As long as the `tomcat8` user has write permissions to the file then lucee should have permission to write to it. For example:

```
# first give tomcat8 ownership of the files
chown -R tomcat8 /web/example.com/wwwroot/uploads/

# then ensure it has write permission
chmod u+w /web/example.com/wwwroot/uploads/
```
