### ISSUE TITLE
webroot question

### ISSUE THREAD

**Issue by jstrong1** [foundeo/ubuntu-nginx-lucee#31]
I ran thru the install, and attempted to configure the default site for lucee: https://gist.github.com/jstrong1/9f280c4d27b57dfa17eeee70b4e64e59

I created an index.cfm file in /web/default/wwwroot/

http://12.34.567.8/ returns the "hello" index.html file as expected.  However, http://12.34.567.8/index.cfm returns: Lucee 5.2.6.59 Error (missinginclude) Page /index.cfm [/var/lib/tomcat8/webapps/ROOT/index.cfm] not found

My expectation was that nginx would server static files from /web/default/wwwroot/, and pass .cfm files to lucee for a response.  Is this not how it is designed to work?

When I copy my index.cfm file to /var/lib/tomcat8/webapps/ROOT, and set permissions on the file:

sudo chown -R tomcat8:tomcat8 /var/lib/tomcat8/webapps/ROOT
sudo chmod -R 750 /var/lib/tomcat8/webapps/ROOT

....http://12.34.567.8/index.cfm returns my index.cfm file correctly.

Does this mean my static files need to live in /web/default/wwwroot/ and my .cfm and .cfc files need to live in /var/lib/tomcat8/webapps/ROOT/?  Or have I misconfigured something?

Any feedback that you could provide would be greatly appreciated.

**Comment by moonpo** [comment]
Hi 

See https://github.com/foundeo/ubuntu-nginx-lucee/issues/18#issuecomment-279879529 for help

**Comment by moonpo** [comment]
After a reboot looks everything works properly no need of the extra line.
