### ISSUE TITLE
Server Config for SSL?

### ISSUE THREAD

**Issue by chrisrodkey** [foundeo/ubuntu-nginx-lucee#37]
I'm attempting to add HTTPS/SSL to my freshly-installed server. My default.conf is reading:

```
server {
  listen 80 default_server;
  server_name example_com;
  root /web/default/wwwroot/;
  index index.html;
  include lucee.conf;
}

server {                 
  listen 443;
  server_name example_com;
  ssl on;
  ssl_certificate /etc/ssl/certs/cert_chain.crt;
  ssl_certificate_key /etc/ssl/private/example_com.key;

  location / {
  root /web/default/wwwroot/;
  index index.html;
  }

  include lucee.conf;
 
}
```

The [mod_cfml documentation](http://viviotech.github.io/mod_cfml/install-nginx.html) for Nginx says I **must** add a $lucee_context parameter when I have "multiple server blocks with the same 'root' value."

However, it also says:

> Make sure you give the $lucee_context variable a unique value. It cannot have the same value in multiple server blocks. Otherwise, multiple sites will share the same Lucee context!

This is the thing: I **want** the multiple sites to share the context. I **want** the port 80 _and_ the port 443 to both redirect to the exact same folder. When I tried to use the same value for $lucee_context in the .conf file, mod_cfml started to poop out new web contexts whenever I'd restart the server, which were very messed up.

Is there a clear and concise way to setup the .conf file so that the same webroot can host both the SSL _and_ HTTP requests? Without causing a scene?

**Comment by kmansel** [comment]
Did you ever get this solved?  This is how you do it in NGINX: 

```
server {
   listen 80 default;
   listen 443 ssl;
   server_name example.com;  
   ssl_certificate /bundled.crt;
   ssl_certificate_key /server.key;
   
   ........
}
```

https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/#a-single-http-https-server

**Comment by pfreitag** [comment]
Hi @chrisrodkey - sorry I missed seeing this until now. What I usually do is setup the http port 80 to redirect to https, so that server doesn't need the web root even set, it can just be as simple as: 

```
server {
	listen 80;
	server_name www.example.com example.com; 
	return 301 https://example.com$request_uri;
}
```

But to also answer your question, if you share the same web root between two `server` blocks and want to share the same lucee server context, then you can set the same value for each `$lucee_context` - not sure why it caused an issue, but it _should_ work.
