### ISSUE TITLE
Tomcat9

### ISSUE THREAD

**Issue by johnceci-m3** [foundeo/ubuntu-nginx-lucee#38]
Any thoughts or plans to update the installer for Tomcat 9?  Wanted to try Ubuntu 20 LTS and that doesn't support Tomcat 8...Going to back down to 16 and pretty sure everything will work from there

**Comment by pfreitag** [comment]
Script now works on Ubuntu 20.04 as of: 418e312bcf5c164d2aa8fc28edad13d630d7bb58
