### ISSUE TITLE
How to restart Lucee via terminal?

### ISSUE THREAD

**Issue by PwrSrg** [foundeo/ubuntu-nginx-lucee#47]
How do I restart the Lucee service via the terminal?

Neither `sudo /opt/lucee/lucee_ctl restart` nor `sudo service lucee_ctl restart` work.

Thank you!

**Comment by pfreitag** [comment]
For this script you would use the `service tomcat restart` or depending on which version of ubuntu the tomcat might have a version number in there, eg `service tomcat9 restart`

**Comment by PwrSrg** [comment]
GREAT.

Didn't realize the Lucee service was actually running as "tomcat9".  Actually didn't even know that was a thing. 😁

Thanks!
