### ISSUE TITLE
Enhancement download Oracle JVM

### ISSUE THREAD

**Issue by mvanleest** [foundeo/ubuntu-nginx-lucee#7]
I will create a pul request for this later, but the following will download the Oracle JVM with curl.

curl -L -O -H "Cookie: oraclelicense=accept-securebackup-cookie" -k "http://download.oracle.com/otn-pub/java/jdk/8u65-b17/server-jre-8u65-linux-x64.tar.gz"

**Comment by pfreitag** [comment]
While it would be handy I'm going to close this issue, because I'm not sure about legal implications of doing this.

You can use the OpenJDK that ships with Ubuntu instead of downloading the Oracle JVM, this has the advantage of the OS updating it using apt-get.
